# Generated by Django 3.2.4 on 2021-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('media_path', models.FileField(max_length=255, null=True, upload_to='posts', verbose_name='Media Path')),
                ('media_type', models.CharField(max_length=50, null=True, verbose_name='Media Type')),
                ('content_type', models.CharField(choices=[('post', 'post'), ('profile', 'profile')], max_length=50, verbose_name='Content type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
