# Generated by Django 3.2.4 on 2021-06-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reaction', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reaction', to='posts.posts', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='reaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reactiontypes', verbose_name='Reaction'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to='posts.comments', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reactiontypes', verbose_name='Reaction'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('author', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('author', 'comment')},
        ),
    ]
