# Generated by Django 3.2.4 on 2021-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Caption'),
        ),
    ]
