# Generated by Django 3.2.4 on 2021-06-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='media_path',
            new_name='media',
        ),
    ]
