# Generated by Django 3.2.4 on 2021-06-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_rename_media_path_posts_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.FileField(max_length=255, null=True, upload_to=helpers.upload_to, verbose_name='Media Path'),
        ),
    ]
