# Generated by Django 3.2.4 on 2021-06-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210626_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media_type',
            field=models.CharField(choices=[(None, None), ('video', 'video/*'), ('image', 'image/*')], max_length=50, null=True, verbose_name='Media Type'),
        ),
    ]
