# Generated by Django 3.2.4 on 2021-06-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_comments_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=50, verbose_name='Reaction Type')),
            ],
            options={
                'verbose_name_plural': 'ReactionTypes',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='post'),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reaction', to='posts.posts', verbose_name='post')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reactiontypes', verbose_name='Reaction')),
            ],
            options={
                'verbose_name_plural': 'PostReactions',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to='posts.comments', verbose_name='comment')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.reactiontypes', verbose_name='Reaction')),
            ],
            options={
                'verbose_name_plural': 'CommentReactions',
            },
        ),
    ]
