# Generated by Django 3.2.4 on 2021-06-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210629_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactiontypes',
            options={'ordering': ['id'], 'verbose_name_plural': 'ReactionTypes'},
        ),
    ]
