# Generated by Django 3.2.4 on 2021-06-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(verbose_name='Follower Id')),
                ('followee_Id', models.IntegerField(verbose_name='Followee Id')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Ia Accepted')),
            ],
        ),
    ]
