# Generated by Django 3.2.4 on 2021-06-23 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'default_related_name': '%(model_name)s', 'get_latest_by': '-created_at', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AddField(
            model_name='followers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 18, 35, 0, 177996, tzinfo=utc), verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='followers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followee_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL, verbose_name='Followee id'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Follower Id'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Is Accepted'),
        ),
    ]
