# Generated by Django 3.2.4 on 2021-06-24 19:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'default_manager_name': 'follower_manager', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelManagers(
            name='followers',
            managers=[
                ('follower_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
