# Generated by Django 3.2.4 on 2021-06-23 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_auto_20210623_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
