# Generated by Django 3.2.4 on 2021-06-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_auto_20210624_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelManagers(
            name='followers',
            managers=[
            ],
        ),
    ]
