# Generated by Django 3.2.4 on 2021-06-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_followers_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followee_Id',
            new_name='followee_id',
        ),
    ]
