# Generated by Django 3.2.4 on 2021-06-24 20:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_auto_20210624_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'base_manager_name': 'relation_manager', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelManagers(
            name='followers',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('relation_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
