# Generated by Django 3.2.4 on 2021-06-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_auto_20210624_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelManagers(
            name='followers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='followers',
            name='is_accepted',
        ),
    ]
