# Generated by Django 3.2.4 on 2021-06-24 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0006_auto_20210624_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to=settings.AUTH_USER_MODEL, verbose_name='Request From')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to=settings.AUTH_USER_MODEL, verbose_name='Request To')),
            ],
            options={
                'verbose_name_plural': 'Follow Requests',
                'unique_together': {('request_from', 'request_to')},
            },
        ),
    ]
