# Generated by Django 3.2.4 on 2021-06-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0009_auto_20210624_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to=settings.AUTH_USER_MODEL, verbose_name='Request From'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to=settings.AUTH_USER_MODEL, verbose_name='Request To'),
        ),
    ]
