# Generated by Django 3.2.4 on 2021-06-23 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_rename_followee_id_followers_followee_id'),
        ('user', '0002_auto_20210618_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(through='followers.Followers', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
