# Generated by Django 3.2.4 on 2021-06-25 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0009_auto_20210624_2320'),
        ('user', '0002_rename_followers_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', through='followers.Followers', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
