# Generated by Django 3.2.4 on 2021-06-26 18:06

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=helpers.upload_to, verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(null=True, verbose_name='Profile Update At'),
        ),
    ]
