# Generated by Django 3.2.4 on 2021-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210626_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private_profile',
            field=models.BooleanField(default=False, verbose_name='Is Private profile'),
        ),
    ]
