# Generated by Django 3.2.4 on 2021-07-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notifications'},
        ),
    ]
